# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1057, 777)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 480, 704, 232))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.up_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.up_btn.setFont(font)
        self.up_btn.setObjectName("up_btn")
        self.verticalLayout.addWidget(self.up_btn)
        self.save_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.cause_name = QtWidgets.QLabel(self.centralwidget)
        self.cause_name.setGeometry(QtCore.QRect(40, 50, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cause_name.setFont(font)
        self.cause_name.setObjectName("cause_name")
        self.keyword = QtWidgets.QLabel(self.centralwidget)
        self.keyword.setGeometry(QtCore.QRect(400, 270, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.keyword.setFont(font)
        self.keyword.setObjectName("keyword")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(770, 50, 220, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.keyword_cnt = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.keyword_cnt.setFont(font)
        self.keyword_cnt.setObjectName("keyword_cnt")
        self.horizontalLayout_2.addWidget(self.keyword_cnt)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 380, 984, 85))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currency_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.currency_btn.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.currency_btn.setFont(font)
        self.currency_btn.setIconSize(QtCore.QSize(20, 20))
        self.currency_btn.setObjectName("currency_btn")
        self.horizontalLayout.addWidget(self.currency_btn)
        self.proper_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.proper_btn.setFont(font)
        self.proper_btn.setObjectName("proper_btn")
        self.horizontalLayout.addWidget(self.proper_btn)
        self.relevant_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.relevant_btn.setFont(font)
        self.relevant_btn.setObjectName("relevant_btn")
        self.horizontalLayout.addWidget(self.relevant_btn)
        self.error_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.error_btn.setFont(font)
        self.error_btn.setObjectName("error_btn")
        self.horizontalLayout.addWidget(self.error_btn)
        self.backLabel = QtWidgets.QLabel(self.centralwidget)
        self.backLabel.setGeometry(QtCore.QRect(310, 150, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.backLabel.setFont(font)
        self.backLabel.setObjectName("backLabel")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.relevant_btn.clicked.connect(mainWindow.set_word_relevant)
        self.pushButton.clicked.connect(mainWindow.selectTxtFilePath)
        self.proper_btn.clicked.connect(mainWindow.set_word_proper)
        self.currency_btn.clicked.connect(mainWindow.set_word_currency)
        self.up_btn.clicked.connect(mainWindow.up_word)
        self.save_btn.clicked.connect(mainWindow.save_word)
        self.error_btn.clicked.connect(mainWindow.set_word_error)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "这是一个数据标注软件"))
        self.up_btn.setText(_translate("mainWindow", "上一个（点错时用）(u)"))
        self.save_btn.setText(_translate("mainWindow", "保存（退出前保存!!!）(s)"))
        self.pushButton.setText(_translate("mainWindow", "选择文件"))
        self.cause_name.setText(_translate("mainWindow", "案由"))
        self.keyword.setText(_translate("mainWindow", "关键词"))
        self.label_3.setText(_translate("mainWindow", "序号："))
        self.keyword_cnt.setText(_translate("mainWindow", "0"))
        self.currency_btn.setText(_translate("mainWindow", "通用词(1)"))
        self.proper_btn.setText(_translate("mainWindow", "专有词(2)"))
        self.relevant_btn.setText(_translate("mainWindow", "关联词(3)"))
        self.error_btn.setText(_translate("mainWindow", "错误(4)"))
        self.backLabel.setText(_translate("mainWindow", "上一步操作内容"))

